apiVersion: v1
kind: Service
metadata:
  labels:
    app: sfblog
  name: sfblog
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: sfblog
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
